/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import { HTMLStencilElement, JSXBase } from "./stencil.core";

export namespace Components {
  interface ArLogotype {}
  interface ArResume {
    showDownloadLink: boolean;
  }
  interface SvgIcon {
    name: string;
    small: boolean;
  }
}

declare global {
  interface HTMLArLogotypeElement
    extends Components.ArLogotype,
      HTMLStencilElement {}
  var HTMLArLogotypeElement: {
    prototype: HTMLArLogotypeElement;
    new (): HTMLArLogotypeElement;
  };

  interface HTMLArResumeElement
    extends Components.ArResume,
      HTMLStencilElement {}
  var HTMLArResumeElement: {
    prototype: HTMLArResumeElement;
    new (): HTMLArResumeElement;
  };

  interface HTMLSvgIconElement extends Components.SvgIcon, HTMLStencilElement {}
  var HTMLSvgIconElement: {
    prototype: HTMLSvgIconElement;
    new (): HTMLSvgIconElement;
  };
  interface HTMLElementTagNameMap {
    "ar-logotype": HTMLArLogotypeElement;
    "ar-resume": HTMLArResumeElement;
    "svg-icon": HTMLSvgIconElement;
  }
}

declare namespace LocalJSX {
  interface ArLogotype {}
  interface ArResume {
    showDownloadLink?: boolean;
  }
  interface SvgIcon {
    name?: string;
    small?: boolean;
  }

  interface IntrinsicElements {
    "ar-logotype": ArLogotype;
    "ar-resume": ArResume;
    "svg-icon": SvgIcon;
  }
}

export { LocalJSX as JSX };

declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      "ar-logotype": LocalJSX.ArLogotype &
        JSXBase.HTMLAttributes<HTMLArLogotypeElement>;
      "ar-resume": LocalJSX.ArResume &
        JSXBase.HTMLAttributes<HTMLArResumeElement>;
      "svg-icon": LocalJSX.SvgIcon & JSXBase.HTMLAttributes<HTMLSvgIconElement>;
    }
  }
}
